### ISSUE TITLE
Scala 3 support (1000USD Bounty)

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/acyclic#76]
---

**From the maintainer Li Haoyi**: I'm putting a 1000USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

The success criteria is that Acyclic's existing test suite all passes when run on Scala 3.4.2 and 3.5.0, and you can show using acyclic in uPickle via `__.publishLocal` and demonstrate it catching import cycles in response to edits

---

**Comment by SethTisue** [comment]
this would be a great project for somebody

**Comment by mrdziuban** [comment]
I'm going to take a stab at this
